# Generated by Django 4.2.4 on 2023-08-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, upload_to='courses/%Y/%m/%d/'),
        ),
    ]
