# Generated by Django 4.2.4 on 2023-08-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='highlight_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
