# Generated by Django 4.2.4 on 2023-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='file',
            field=models.FileField(blank=True, upload_to='newsletters/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
